###########################
# Configuration for rubocop
# in .rubocop.yml 
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.
AllCops:
  Exclude:
    - 'examples/*.rb'

Style/SpaceInsideBlockBraces:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
